export const LOGIN_FETCH = 'LOGIN_FETCH';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_FETCH = 'LOGOUT_FETCH';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_USERS_FETCH = 'GET_USERS_FETCH';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const GET_CURRENT_USER_FETCH = 'GET_CURRENT_USER_FETCH';
export const GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';

export const GET_USER_DATA_FETCH = 'GET_USER_DATA_FETCH';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR';

export const DELETE_USER_LABEL_FETCH = 'DELETE_USER_LABEL_FETCH';
export const DELETE_USER_LABEL_ERROR = 'DELETE_USER_LABEL_ERROR';

export const ADD_USER_LABEL_FETCH = 'ADD_USER_LABEL_FETCH';
export const ADD_USER_LABEL_ERROR = 'ADD_USER_LABEL_ERROR';

export const CHANGE_USER_STATE_FETCH = 'CHANGE_USER_STATE_FETCH';
export const CHANGE_USER_STATE_ERROR = 'CHANGE_USER_STATE_ERROR';
